import 'package:alpen_ai_camera/domain/entities/pose_landmark.dart';
import 'package:alpen_ai_camera/domain/entities/pose_outline_point.dart';
import 'package:alpen_ai_camera/domain/entities/pose_template.dart';

class DefaultPoseTemplates {
  DefaultPoseTemplates._();

  static const List<PoseTemplate> all = <PoseTemplate>[
    PoseTemplate(
      templateId: 'default-hands-waist',
      name: 'Tangan di Pinggang',
      outlinePoints: <PoseOutlinePoint>[
        PoseOutlinePoint(x: 0.50, y: 0.07),
        PoseOutlinePoint(x: 0.42, y: 0.09),
        PoseOutlinePoint(x: 0.36, y: 0.16),
        PoseOutlinePoint(x: 0.35, y: 0.26),
        PoseOutlinePoint(x: 0.27, y: 0.34),
        PoseOutlinePoint(x: 0.22, y: 0.44),
        PoseOutlinePoint(x: 0.28, y: 0.52),
        PoseOutlinePoint(x: 0.39, y: 0.51),
        PoseOutlinePoint(x: 0.38, y: 0.62),
        PoseOutlinePoint(x: 0.36, y: 0.78),
        PoseOutlinePoint(x: 0.33, y: 0.96),
        PoseOutlinePoint(x: 0.45, y: 0.98),
        PoseOutlinePoint(x: 0.49, y: 0.68),
        PoseOutlinePoint(x: 0.52, y: 0.68),
        PoseOutlinePoint(x: 0.55, y: 0.98),
        PoseOutlinePoint(x: 0.67, y: 0.96),
        PoseOutlinePoint(x: 0.64, y: 0.78),
        PoseOutlinePoint(x: 0.62, y: 0.62),
        PoseOutlinePoint(x: 0.61, y: 0.51),
        PoseOutlinePoint(x: 0.72, y: 0.52),
        PoseOutlinePoint(x: 0.78, y: 0.44),
        PoseOutlinePoint(x: 0.73, y: 0.34),
        PoseOutlinePoint(x: 0.65, y: 0.26),
        PoseOutlinePoint(x: 0.64, y: 0.16),
        PoseOutlinePoint(x: 0.58, y: 0.09),
      ],
      landmarks: <PoseLandmark>[
        PoseLandmark(name: 'nose', x: 0.50, y: 0.15, visibility: 1),
        PoseLandmark(name: 'leftShoulder', x: 0.38, y: 0.28, visibility: 1),
        PoseLandmark(name: 'rightShoulder', x: 0.62, y: 0.28, visibility: 1),
        PoseLandmark(name: 'leftElbow', x: 0.30, y: 0.43, visibility: 1),
        PoseLandmark(name: 'rightElbow', x: 0.70, y: 0.43, visibility: 1),
        PoseLandmark(name: 'leftWrist', x: 0.42, y: 0.53, visibility: 1),
        PoseLandmark(name: 'rightWrist', x: 0.58, y: 0.53, visibility: 1),
        PoseLandmark(name: 'leftHip', x: 0.43, y: 0.55, visibility: 1),
        PoseLandmark(name: 'rightHip', x: 0.57, y: 0.55, visibility: 1),
        PoseLandmark(name: 'leftKnee', x: 0.42, y: 0.78, visibility: 1),
        PoseLandmark(name: 'rightKnee', x: 0.58, y: 0.78, visibility: 1),
        PoseLandmark(name: 'leftAnkle', x: 0.40, y: 0.96, visibility: 1),
        PoseLandmark(name: 'rightAnkle', x: 0.60, y: 0.96, visibility: 1),
      ],
    ),
    PoseTemplate(
      templateId: 'default-one-arm-up',
      name: 'Satu Tangan Naik',
      outlinePoints: <PoseOutlinePoint>[
        PoseOutlinePoint(x: 0.50, y: 0.08),
        PoseOutlinePoint(x: 0.42, y: 0.10),
        PoseOutlinePoint(x: 0.36, y: 0.17),
        PoseOutlinePoint(x: 0.34, y: 0.28),
        PoseOutlinePoint(x: 0.28, y: 0.38),
        PoseOutlinePoint(x: 0.24, y: 0.54),
        PoseOutlinePoint(x: 0.34, y: 0.57),
        PoseOutlinePoint(x: 0.42, y: 0.52),
        PoseOutlinePoint(x: 0.40, y: 0.64),
        PoseOutlinePoint(x: 0.38, y: 0.80),
        PoseOutlinePoint(x: 0.35, y: 0.97),
        PoseOutlinePoint(x: 0.47, y: 0.98),
        PoseOutlinePoint(x: 0.50, y: 0.69),
        PoseOutlinePoint(x: 0.54, y: 0.69),
        PoseOutlinePoint(x: 0.59, y: 0.98),
        PoseOutlinePoint(x: 0.70, y: 0.96),
        PoseOutlinePoint(x: 0.66, y: 0.78),
        PoseOutlinePoint(x: 0.62, y: 0.56),
        PoseOutlinePoint(x: 0.69, y: 0.35),
        PoseOutlinePoint(x: 0.75, y: 0.18),
        PoseOutlinePoint(x: 0.73, y: 0.03),
        PoseOutlinePoint(x: 0.65, y: 0.02),
        PoseOutlinePoint(x: 0.62, y: 0.24),
        PoseOutlinePoint(x: 0.64, y: 0.32),
        PoseOutlinePoint(x: 0.58, y: 0.10),
      ],
      landmarks: <PoseLandmark>[
        PoseLandmark(name: 'nose', x: 0.50, y: 0.15, visibility: 1),
        PoseLandmark(name: 'leftShoulder', x: 0.38, y: 0.28, visibility: 1),
        PoseLandmark(name: 'rightShoulder', x: 0.62, y: 0.28, visibility: 1),
        PoseLandmark(name: 'leftElbow', x: 0.31, y: 0.40, visibility: 1),
        PoseLandmark(name: 'rightElbow', x: 0.68, y: 0.16, visibility: 1),
        PoseLandmark(name: 'leftWrist', x: 0.28, y: 0.54, visibility: 1),
        PoseLandmark(name: 'rightWrist', x: 0.70, y: 0.04, visibility: 1),
        PoseLandmark(name: 'leftHip', x: 0.43, y: 0.55, visibility: 1),
        PoseLandmark(name: 'rightHip', x: 0.57, y: 0.55, visibility: 1),
        PoseLandmark(name: 'leftKnee', x: 0.41, y: 0.78, visibility: 1),
        PoseLandmark(name: 'rightKnee', x: 0.60, y: 0.78, visibility: 1),
        PoseLandmark(name: 'leftAnkle', x: 0.39, y: 0.96, visibility: 1),
        PoseLandmark(name: 'rightAnkle', x: 0.62, y: 0.96, visibility: 1),
      ],
    ),
  ];
}
